brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "romkatv/powerlevel10k/powerlevel10k"

brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "neofetch"
brew "ripgrep"
brew "tmux"

brew "pyenv"
brew "pyenv-virtualenv"

brew "hadolint"
brew "shellcheck"
brew "shfmt"
brew "stylua"
