#!/bin/bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/_base.sh

echo "Configuring macOS"
if [[ "$(uname)" == "Darwin" ]]; then
  source $DOTFILES_ROOT/macos/set-defaults.sh
fi
