#!/bin/bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/_base.sh

echo "Setup package manager"
if [[ "$(uname)" == "Darwin" ]]; then
  echo "Configuring homebrew"
  bash $DOTFILES_ROOT/homebrew/install.sh
elif [[ "$(uname)" == "Linux" ]]; then
  echo "Configuring apt"
  bash $DOTFILES_ROOT/apt/install.sh
fi
