#!/bin/bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/_base.sh

while read src; do
  dst_dir="$(dirname "$HOME/${src#$DOTFILES_ROOT/*/}")"
  dst_file="$(basename ${src/.symlink})"
  dst="$dst_dir/$dst_file"
  unlink "$dst"
done < <(find $DOTFILES_ROOT -name *.symlink*)
