# These are the GNU core utilities.
# https://github.com/coreutils/coreutils
brew 'coreutils'

# A modern replacement for ls.
# https://the.exa.website/
brew 'exa'

# A line-oriented search tool that recursively searches the current directory for a regex pattern.
# https://github.com/BurntSushi/ripgrep
brew 'ripgrep'

# A command-line fuzzy finder
# https://github.com/junegunn/fzf
brew 'fzf'

# A cat(1) clone with wings.
# https://github.com/sharkdp/bat
brew 'bat'

# A shell parser, formatter, and interpreter with bash support
# https://github.com/mvdan/sh
brew 'shfmt'

# ShellCheck, a static analysis tool for shell scripts
# https://github.com/koalaman/shellcheck
brew 'shellcheck'

# Terminal multiplexer
# https://github.com/tmux/tmux
brew 'tmux'

# Vim-fork focused on extensibility and usability
# https://github.com/neovim/neovim
brew 'neovim'

# A cross-platform, OpenGL terminal emulator.
# https://github.com/alacritty/alacritty
cask 'alacritty'
