#!/bin/bash

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $__dir/_base.sh

while read src; do
  dst="$(dirname "$HOME/${src#$DOTFILES_ROOT/*/}")/$(basename ${src%.*})"
  unlink "$dst"
done < <(find $DOTFILES_ROOT -name *.symlink)
