#!/bin/sh

DOTFILES="$HOME/.dotfiles"

if ! [ -d "$DOTFILES" ]; then
  echo "The \$DOTFILES folder dones't exists ($DOTFILES). Please use this script with dotfiles."
  exit 1
fi

DOTS="$DOTFILES/dots"
XDG_CONFIG_HOME="$HOME/.config"
REMOTE=https://github.com/peterhpchen/dotfiles.git
INSTALL_SCRIPT="$DOTFILES/.scripts/install.ubuntu.sh"

rm -f "$INSTALL_SCRIPT"

cat >"$INSTALL_SCRIPT" <<EOF
#!/bin/sh

# Generated by gen-single-script.ubuntu.sh

EOF

. "$DOTS/apt/.scripts/gen-single-script.sh" >>"$INSTALL_SCRIPT"
